# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb7f22244f4e2c409c6fedbc82329f8b9f658435a96aee8c8c47691f77797e1e7b9742e7fb4d20ac95522172ec2604cfa6778268885f56169a250cf9c681b0a

test:
  secret_key_base: 19e376704af069e6471b7203816c2b89639d380b8f93682968a5cfe34f57eac8abb8a83c2459b07eac7fb4d6b671f911739e58e891461783cb876b9f94bb2516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
